version: '3.8'
services:
#  web:
#    build:
#      context: cloud-store-service
#    depends_on:
#      - mongo
#    ports:
#      - "8080:8080"
#      - "5000:5000"
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./env/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafanad
    env_file:
      - ./env/grafana.env
volumes:
  grafana-data: