global:
  scrape_interval: 15s
  query_log_file: /prometheus/query.log
  external_labels:
    monitor: 'cloud-event-store'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'cloud-event-store'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]