name: Deploy
on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker
      - name: Build native executable
        uses: maxday/quarkus-native-build-docker-action@master
        with:
          dockerfilePath: cloud-store/src/main/docker/Dockerfile.native
          outputName: app-runner
      - name: Dockerize
        id: dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: kcybulski.me/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}
          executablePath: app-runner
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - name: Push the Docker image to GCP
        run: |
          gcloud auth configure-docker --quiet
          docker push kcybulski.me/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}
      - name: Deploy
        run: |
          gcloud components install beta --quiet
          gcloud beta run deploy ${{ secrets.GCP_APP_NAME }} \
          --image kcybulski.me/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }} \
          --platform ${{ secrets.GCP_PLATFORM }} \
          --allow-unauthenticated --service-account ${{ secrets.GCP_EMAIL }} \
          --region ${{ secrets.GCP_REGION }} \
          --set-env-vars DISABLE_SIGNAL_HANDLERS=1